# FEPRO - Federation Professionals
# Docker Compose configuration for production deployment
version: '3.8'

services:
  # Main application service
  fepro-app:
    build: .
    container_name: fepro-app
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fepro_prod
      - SPRING_DATASOURCE_USERNAME=fepro_user
      - SPRING_DATASOURCE_PASSWORD=fepro_pass
      - HAZELCAST_ENABLED=true
      - HAZELCAST_CLUSTER_NAME=fepro-cluster
      - HAZELCAST_NETWORK_PORT=5701
      - HAZELCAST_MANAGEMENT_CENTER_ENABLED=false
      - SERVER_PORT=8082
      - SERVER_SERVLET_CONTEXT_PATH=/api
      - LOGGING_LEVEL_COM_FEPRO=INFO
      - LOGGING_FILE_NAME=/app/logs/fepro.log
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    restart: unless-stopped
    networks:
      - fepro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # PostgreSQL database service
  postgres:
    image: postgres:16-alpine
    container_name: fepro-postgres
    environment:
      - POSTGRES_DB=fepro_prod
      - POSTGRES_USER=fepro_user
      - POSTGRES_PASSWORD=fepro_pass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
      - ./backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - fepro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fepro_user -d fepro_prod"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres

# Network configuration
networks:
  fepro-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16