spring:
  application:
    name: fepro-backend
  
  # Database Configuration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fepro_db
    username: fepro_user
    password: fepro_pass
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      max-acquire-time: 30s
      max-create-connection-time: 30s
      max-life-time: 1h
  
  datasource:
    url: jdbc:postgresql://localhost:5432/fepro_db
    username: fepro_user
    password: fepro_pass
    driver-class-name: org.postgresql.Driver
  
  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # GraphQL Configuration
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
  
  # Security Configuration
  security:
    jwt:
      secret: fepro-jwt-secret-key-that-is-very-long-and-secure
      expiration: 86400000 # 24 hours
  
  # Mail Configuration (for notifications)
  mail:
    host: localhost
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server Configuration
server:
  port: 8082
  servlet:
    context-path: /
  
# Logging Configuration
logging:
  level:
    io.github.bondalen.fepro: DEBUG
    org.springframework.r2dbc: DEBUG
    org.springframework.graphql: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Application specific configuration
fepro:
  app:
    name: FEPRO
    version: 1.0.0
    description: Federation Professionals - система управления контрагентами
  
  # Pagination defaults
  pagination:
    default-size: 20
    max-size: 100
  
  # File upload configuration
  upload:
    max-file-size: 10MB
    allowed-extensions: pdf,doc,docx,xls,xlsx,csv
  
  # GIS configuration
  gis:
    default-srid: 4326
    default-radius: 1000 # meters